spring.application.name=backend
server.port=5050

spring.datasource.url=jdbc:mysql://127.0.0.1:3306/srg
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update

# spirng.security.user.name=admin
# spirng.security.user.password=1234